Change CLIENT_ID to CLIENT_NAME
aerogearcatalog/custom-runtime-connector-apb pull request #15
Opened 2018-04-19 11:38 UTC by sedroche

I believe we are going we `CLIENT_NAME` now so these are the changes for the CRC.

2018-04-19 11:39 UTC, sedroche commented
@dimitraz @vchepeli

2018-04-19 11:43 UTC, dimitraz approved these changes
:+1:

2018-04-19 15:01 UTC, ghost requested changes

2018-04-19 15:01 UTC, vchepeli commented on roles/test-crc-apb/vars/main.yml
> +CLIENT_NAME: 'MyClientId'
should be 'MyClientIdName'

2018-04-19 16:30 UTC, ghost requested changes

2018-04-19 16:30 UTC, vchepeli commented on apb.yml
>        title: Mobile Client Id
title: Mobile Client Name

2018-04-19 16:34 UTC, ghost requested changes

2018-04-19 16:34 UTC, vchepeli commented on roles/bind-crc-apb/tasks/main.yml
> +      mobileClientId: '{{ CLIENT_NAME }}'
should be `clientId: '{{ CLIENT_NAME }}'`

2018-04-19 16:34 UTC, vchepeli commented on roles/bind-crc-apb/tasks/main.yml
>        mobile-client: "enabled"
should be  `mobile-client: '{{ crc_svc_label_mobile }}'`

2018-04-20 09:06 UTC, ghost approved these changes

2018-04-20 11:37 UTC, merged