move from configmap to secret
aerogearcatalog/custom-runtime-connector-apb pull request #9
Opened 2018-04-17 16:11 UTC by witmicko

JIRA:
https://issues.jboss.org/browse/AEROGEAR-2421

@maleck13 @philbrookes

2018-04-17 16:16 UTC, maleck13 requested changes
Am i missing something? Where is the config field with the config data as a string?

2018-04-17 16:22 UTC, witmicko commented
@maleck13 it was already there so it is not showing up in the diff 
https://github.com/witmicko/custom-runtime-connector-apb/blob/effc64b660e8c2efa4e99005a7e6662d249cd52b/roles/bind-crc-apb/tasks/main.yml#L45

2018-04-18 08:02 UTC, maleck13 commented
@witmicko ahh ok. Do you want to add some verification steps @vchepeli might something you can help with here

2018-04-18 08:06 UTC, maleck13 commented on roles/bind-crc-apb/tasks/main.yml
> +      mobile-client: "enabled"
This should be under labels

2018-04-18 08:06 UTC, maleck13 reviewed
minor change plus some verification steps

2018-04-18 08:19 UTC, witmicko commented on roles/bind-crc-apb/tasks/main.yml
> +      mobile-client: "enabled"
@maleck13 it is, short diff strikes again :) - click on those expand icons to see more of the file
will add verification

2018-04-18 08:28 UTC, maleck13 approved these changes

2018-04-18 13:50 UTC, maleck13 commented
@witmicko checking this out now

2018-04-18 14:36 UTC, maleck13 commented
Verified this locally. Have we tagged the previous version and then we can merge
@david-martin  @aliok  FYI we will tag the previous version which should create a tagged image in dockerhub and then latest will be the new client binding flow

2018-04-18 14:44 UTC, david-martin commented
@maleck13 A tag of the previous version would be good to have repeatable/reliable steps for demo recording

2018-04-18 14:58 UTC, maleck13 commented
Yes i have tagged master

2018-04-18 14:58 UTC, merged